"""Add created_at field to Like model

Revision ID: 083538752579
Revises: c78f65ea802a
Create Date: 2023-09-28 12:33:00.418055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '083538752579'
down_revision: Union[str, None] = 'c78f65ea802a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('likes', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('likes', 'created_at')
    # ### end Alembic commands ###
